- project:
    check:
      jobs:
        - openstack-tacker-tox-docs
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tacker-tox-docs
        - openstack-tox-pep8

- job:
    name: openstack-tacker-tox-docs
    parent: openstack-tox-docs
    pre-run: playbooks/pre.yaml
